spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password: sa
server:
  port: 8080
logging:
  level:
    liquibase: INFO